/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    products: Product;
    brands: Brand;
    categories: Category;
    lookbooks: Lookbook;
    pages: Page;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    products: ProductsSelect<false> | ProductsSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    lookbooks: LookbooksSelect<false> | LookbooksSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | 'it' | 'it'[];
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: 'it';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  nome: string;
  /**
   * Generato dal nome se lasciato vuoto. Usato negli URL: modifica con cautela.
   */
  slug: string;
  /**
   * Codice univoco. Chiave per import e nomi file foto ({SKU}-01.jpg).
   */
  sku: string;
  brand: number | Brand;
  categoria: number | Category;
  descrizione?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * La prima immagine è quella principale (copertina).
   */
  immagini?: (number | Media)[] | null;
  prezzo?: number | null;
  prezzoSuRichiesta?: boolean | null;
  /**
   * Le taglie attese dipendono dal sistema taglie della categoria.
   */
  taglie?:
    | {
        taglia: string;
        disponibile?: boolean | null;
        id?: string | null;
      }[]
    | null;
  colori?:
    | {
        nome: string;
        hex?: string | null;
        id?: string | null;
      }[]
    | null;
  stagione?: {
    tipo?: ('PE' | 'AI') | null;
    anno?: number | null;
  };
  /**
   * Numero più basso = mostrato prima. Lascia 0 per l’ordine alfabetico.
   */
  ordine?: number | null;
  inEvidenza?: boolean | null;
  /**
   * Se disattivato, il prodotto resta visibile ma segnalato come non disponibile.
   */
  disponibile?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  nome: string;
  /**
   * Generato dal nome se lasciato vuoto. Usato negli URL: modifica con cautela.
   */
  slug: string;
  logo?: (number | null) | Media;
  descrizione?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  sito?: string | null;
  /**
   * Numero più basso = mostrato prima. Lascia 0 per l’ordine alfabetico.
   */
  ordine?: number | null;
  /**
   * Mostra il marchio nel “muro dei marchi” della homepage. Se nessun marchio è spuntato, la home li mostra tutti.
   */
  inEvidenzaHome?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descrizione dell’immagine per accessibilità e SEO.
   */
  alt: string;
  caption?: string | null;
  cloudinaryPublicId?: string | null;
  cloudinaryUrl?: string | null;
  cloudinaryResourceType?: string | null;
  cloudinaryFormat?: string | null;
  cloudinaryVersion?: number | null;
  /**
   * Direct URL to the original file without transformations
   */
  originalUrl?: string | null;
  /**
   * URL with applied transformations
   */
  transformedUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  /**
   * File size in bytes
   */
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  nome: string;
  /**
   * Generato dal nome se lasciato vuoto. Usato negli URL: modifica con cautela.
   */
  slug: string;
  ordine?: number | null;
  /**
   * Determina le taglie suggerite per i prodotti di questa categoria.
   */
  sizeType: 'alpha' | 'numeric_eu' | 'shoe_eu' | 'one_size' | 'custom';
  customSizes?:
    | {
        taglia: string;
        id?: string | null;
      }[]
    | null;
  descrizione?: string | null;
  immagine?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lookbooks".
 */
export interface Lookbook {
  id: number;
  titolo: string;
  /**
   * Generato dal nome se lasciato vuoto. Usato negli URL: modifica con cautela.
   */
  slug: string;
  stagione?: {
    tipo?: ('PE' | 'AI') | null;
    anno?: number | null;
  };
  descrizione?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  immagini: (number | Media)[];
  brandsCorrelati?: (number | Brand)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  titolo: string;
  /**
   * Generato dal nome se lasciato vuoto. Usato negli URL: modifica con cautela.
   */
  slug: string;
  /**
   * Breve introduzione mostrata in cima alla pagina.
   */
  sommario?: string | null;
  immagine?: (number | null) | Media;
  contenuto: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Gli amministratori gestiscono utenti e impostazioni.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'lookbooks';
        value: number | Lookbook;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  nome?: T;
  slug?: T;
  sku?: T;
  brand?: T;
  categoria?: T;
  descrizione?: T;
  immagini?: T;
  prezzo?: T;
  prezzoSuRichiesta?: T;
  taglie?:
    | T
    | {
        taglia?: T;
        disponibile?: T;
        id?: T;
      };
  colori?:
    | T
    | {
        nome?: T;
        hex?: T;
        id?: T;
      };
  stagione?:
    | T
    | {
        tipo?: T;
        anno?: T;
      };
  ordine?: T;
  inEvidenza?: T;
  disponibile?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  nome?: T;
  slug?: T;
  logo?: T;
  descrizione?: T;
  sito?: T;
  ordine?: T;
  inEvidenzaHome?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  nome?: T;
  slug?: T;
  ordine?: T;
  sizeType?: T;
  customSizes?:
    | T
    | {
        taglia?: T;
        id?: T;
      };
  descrizione?: T;
  immagine?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lookbooks_select".
 */
export interface LookbooksSelect<T extends boolean = true> {
  titolo?: T;
  slug?: T;
  stagione?:
    | T
    | {
        tipo?: T;
        anno?: T;
      };
  descrizione?: T;
  immagini?: T;
  brandsCorrelati?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  titolo?: T;
  slug?: T;
  sommario?: T;
  immagine?: T;
  contenuto?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  cloudinaryPublicId?: T;
  cloudinaryUrl?: T;
  cloudinaryResourceType?: T;
  cloudinaryFormat?: T;
  cloudinaryVersion?: T;
  originalUrl?: T;
  transformedUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  ragioneSociale?: string | null;
  partitaIva?: string | null;
  indirizzo?: {
    via?: string | null;
    civico?: string | null;
    cap?: string | null;
    citta?: string | null;
    provincia?: string | null;
  };
  telefono?: string | null;
  email?: string | null;
  /**
   * Es. 393331234567. Se vuoto si usa NEXT_PUBLIC_WHATSAPP_NUMBER. Il fisso non vale per WhatsApp.
   */
  whatsappNumber?: string | null;
  formspreeEndpoint?: string | null;
  orari?:
    | {
        giorni?: string | null;
        orario?: string | null;
        chiuso?: boolean | null;
        id?: string | null;
      }[]
    | null;
  social?: {
    instagram?: string | null;
    facebook?: string | null;
  };
  mappa?: {
    lat?: number | null;
    lng?: number | null;
    googleMapsUrl?: string | null;
  };
  /**
   * Foto per la pagina Contatti (taglio orizzontale, accanto al cartellino del negozio). Vuoto = usa la Foto 2 di Chi siamo.
   */
  contattiFoto?: (number | null) | Media;
  /**
   * Opzionale. Foto o breve video di sfondo per la home: appare dietro al wordmark con un velo scuro (il wordmark diventa chiaro). Vuoto = hero tipografico chiaro.
   */
  heroMedia?: (number | null) | Media;
  /**
   * Foto verticale per la sezione "La nostra storia". Vuoto = pannello materico.
   */
  chiSiamoFoto1?: (number | null) | Media;
  /**
   * Foto VERTICALE dell’interno del negozio per la sezione "Vieni a trovarci" di Chi siamo. Vuoto = pannello materico.
   */
  chiSiamoFoto2?: (number | null) | Media;
  seoDefault?: {
    titolo?: string | null;
    descrizione?: string | null;
    immagine?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  ragioneSociale?: T;
  partitaIva?: T;
  indirizzo?:
    | T
    | {
        via?: T;
        civico?: T;
        cap?: T;
        citta?: T;
        provincia?: T;
      };
  telefono?: T;
  email?: T;
  whatsappNumber?: T;
  formspreeEndpoint?: T;
  orari?:
    | T
    | {
        giorni?: T;
        orario?: T;
        chiuso?: T;
        id?: T;
      };
  social?:
    | T
    | {
        instagram?: T;
        facebook?: T;
      };
  mappa?:
    | T
    | {
        lat?: T;
        lng?: T;
        googleMapsUrl?: T;
      };
  contattiFoto?: T;
  heroMedia?: T;
  chiSiamoFoto1?: T;
  chiSiamoFoto2?: T;
  seoDefault?:
    | T
    | {
        titolo?: T;
        descrizione?: T;
        immagine?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}